### ISSUE TITLE
Transition tiles do not connect properly

### ISSUE THREAD

**Issue by jaythebusinessgoose** [spelunky-fyi/overlunky#236]
When the game is launched through Playlunky, or when Overlunky is launched in a vanilla game, the tiles in transitions don't connect properly. Tiles that are supposed to be 2-tall connections draw only the bottom half twice. Or it could be that a bottom half of a connection tile is being used in random places instead of just with its top half.

See the Playlunky issue for more context: https://github.com/spelunky-fyi/Playlunky/issues/24

**Comment by Dregu** [comment]
This glitch is so obvious now, why hasn't anyone reported it before... The funny floors have -2 as their animation frame, which is suspiciously also their default texture id. I believe they are supposed to default to animation frame 0, which happens when I remove the following code.

I narrowed it down to [this weird asm block](https://github.com/spelunky-fyi/overlunky/blob/main/src/game_api/render_api.cpp#L341-L360). Well, didn't really have to do much narrowing, the first thing I thought was "it's probably that weird asm block with the funny comment".

**Comment by Malacath-92** [comment]
Should be fixed in [088a27e](https://github.com/spelunky-fyi/overlunky/commit/088a27eca8b4ccdb5f249d04a200c7398e076d50)
