### ISSUE TITLE
Instantly crashes when the injection is finished

### ISSUE THREAD

**Issue by Kombupig** [spelunky-fyi/overlunky#6]
impossible to use, I'm using the latest version

**Comment by BigLionbruh** [comment]
Yeah this happened to me a bit too, but depending on when you start the injection this shouldn't happen (I think). If you start it in the same first few seconds as spelunky 2 is launching, at least for me it shouldn't crash. Also friendly tip don't put "402" into the entity spawner because it instantly crashes the game

**Comment by iojon** [comment]
I think this should be fixed together with #4 by fcde1b2.
